name: Destroy

on:
  workflow_dispatch:

concurrency: ${{ github.ref }}

jobs:
  Plan:
    runs-on: ubuntu-latest
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
    if: contains(fromJson('["master"]'), github.ref_name)

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -destroy -input=false

      - name: Cache repository
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ github.repository }}-${{ github.sha }}-${{ runner.os }}
        continue-on-error: true

  Destroy:
    runs-on: ubuntu-latest
    environment: Jenkins
    needs: Plan
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
    if: contains(fromJson('["master"]'), github.ref_name) && !(failure() || cancelled())

    steps:
      - name: Terraform cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ github.repository }}-${{ github.sha }}-${{ runner.os }}
        continue-on-error: true

      - uses: actions/checkout@v3
        if: steps.cache.outputs.cache-hit != 'true'

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        if: steps.cache.outputs.cache-hit != 'true'
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false

  Cleanup:
    runs-on: ubuntu-latest
    needs: Destroy
    if: contains(fromJson('["master"]'), github.ref_name) && always()

    steps:
      - name: Delete cache
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/caches?key=${{ github.repository }}-${{ github.sha }}-${{ runner.os }}
        continue-on-error: true
