name: Terraform

on:
  workflow_run:
    workflows:
      - Validate
    types:
      - completed
    branches:
      - master
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  Plan:
    runs-on: ubuntu-latest
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
    if: github.event.workflow_run.conclusion != 'failure' && github.ref_name == 'master'

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false

      - uses: actions/github-script@v6
        if: github.event.workflow_run.event == 'pull_request'
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
            })
            
            // 2. Prepare format of the comment
            const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
            
            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }

      - name: Cache repository
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ github.repository }}-${{ github.sha }}-${{ runner.os }}
        continue-on-error: true

  Apply:
    runs-on: ubuntu-latest
    environment:
      name: Jenkins
      url: ${{ steps.output.outputs.stdout }}
    needs: Plan
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
    if: github.event.workflow_run.conclusion != 'failure' && github.ref_name == 'master'

    steps:
      - name: Terraform cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ github.repository }}-${{ github.sha }}-${{ runner.os }}
        continue-on-error: true

      - uses: actions/checkout@v3
        if: steps.cache.outputs.cache-hit != 'true'

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        if: steps.cache.outputs.cache-hit != 'true'
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      - name: Terraform Output
        id: output
        run: terraform output -raw jenkins_url

  Cleanup:
    runs-on: ubuntu-latest
    needs: [ Plan, Apply ]
    if: always() && github.ref_name == 'master'

    steps:
      - name: Delete cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/caches?key=${{ github.repository }}-${{ github.sha }}-${{ runner.os }}
        continue-on-error: true
