name: Terraform

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.github/workflows/*.yml'
      - '!.github/workflows/terraform.yml'
      - 'README.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '.github/workflows/*.yml'
      - '!.github/workflows/terraform.yml'
      - 'README.md'

jobs:
  Validate:
    runs-on: ubuntu-latest
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Cache repository
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ github.repository }}-${{ github.sha }}-${{ runner.os }}

    outputs:
      fmt_outcome: ${{ steps.fmt.outcome }}
      validate_outcome: ${{ steps.validate.outcome }}
      validate_stdout: ${{ steps.validate.outputs.stdout }}

  Plan:
    runs-on: ubuntu-latest
    needs: Validate
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
    if: ${{ false }}

    steps:
      - name: Terraform cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ github.repository }}-${{ github.sha }}-${{ runner.os }}

      - uses: actions/checkout@v3
        if: steps.cache.outputs.cache-hit != 'true'

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        if: steps.cache.outputs.cache-hit != 'true'
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -input=false

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
            })

            // 2. Prepare format of the comment
            const output = `#### Terraform Format and Style 🖌\`${{ needs.Validate.outputs.fmt_outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ needs.Validate.outputs.validate_outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ needs.Validate.outputs.validate_stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${{ steps.plan.outputs.stdout }}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }

      - name: Delete unused cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/caches?key=${{ github.repository }}-${{ github.sha }}-${{ runner.os }}

      - name: Cache repository
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ github.repository }}-${{ github.sha }}-${{ runner.os }}

  Apply:
    runs-on: ubuntu-latest
    environment:
      name: Jenkins
      url: ${{ steps.output.outputs.stdout }}
    needs: Plan
    env:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
    if: ${{ false }}

    steps:
      - name: Terraform cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ github.repository }}-${{ github.sha }}-${{ runner.os }}

      - uses: actions/checkout@v3
        if: steps.cache.outputs.cache-hit != 'true'

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        if: steps.cache.outputs.cache-hit != 'true'
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -input=false tfplan

      - name: Terraform Output
        id: output
        run: terraform output -raw jenkins_url

  Cleanup:
    runs-on: ubuntu-latest
    needs: [ Validate, Plan, Apply ]
    if: ${{ always() }}

    steps:
      - name: Delete cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/caches?key=${{ github.repository }}-${{ github.sha }}-${{ runner.os }}
        continue-on-error: true
