name: tfsec

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ '.github/workflows/*.yml', '!.github/workflows/tfsec.yml', 'README.md' ]
  pull_request:
    paths-ignore: [ '.github/workflows/*.yml', '!.github/workflows/tfsec.yml', 'README.md' ]

jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Scan
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif
